version: '2'
services:
  database:
    build: database
    container_name: jenio_database
    hostname: jenio_database
    restart: on-failure
    ports:
      - "27017:27017"
  payment-api:
    build: payment-api
    container_name: jenio_payment_api
    hostname: jenio_payment_api
    restart: on-failure
    links:
      - database
    depends_on:
      - database
    environment:
      - PORT=1337
      - MONGO_HOST=jenio_database
      - MONGO_PORT=27017
      - MONGO_DB=admin
    ports:
      - "1337:1337"